<?php

return array (
  'name' => '我的网站',
  'beian' => '',
  'cdnurl' => '',
  'version' => '1.0.1',
  'timezone' => 'Asia/Shanghai',
  'forbiddenip' => '',
  'languages' => 
  array (
    'backend' => 'zh-cn',
    'frontend' => 'zh-cn',
  ),
  'fixedpage' => 'dashboard',
  'categorytype' => 
  array (
    'default' => '默认',
    'page' => '单页',
    'article' => '文章',
    'test' => 'Test',
  ),
  'configgroup' => 
  array (
    'basic' => '基础配置',
    'email' => '邮件配置',
    'dictionary' => '字典配置',
    'user' => '会员配置',
    'api' => 'API配置',
    'draft' => '草稿配置',
    'prompt' => '提示词配置',
    'task' => '任务配置',
  ),
  'mail_type' => '1',
  'mail_smtp_host' => 'smtp.qq.com',
  'mail_smtp_port' => '465',
  'mail_smtp_user' => '10000',
  'mail_smtp_pass' => 'password',
  'mail_verify_type' => '2',
  'mail_from' => '10000@qq.com',
  'attachmentcategory' => 
  array (
    'category1' => '分类一',
    'category2' => '分类二',
    'custom' => '自定义',
  ),
  'openai_api_key' => 'sk-laAJIQZ6r8G4YN003ehpD7JgsqollgHO6uzAL2IaQcW2HVmU',
  'access_key_id' => 'LTAI5t8c2T46dF8fpSHhQpVq',
  'access_key_secret' => 'gZSN1WxSFC7DuHzUeUXcdL4tBcujxh',
  'draft_removable_storage_device' => 'D:',
  'draft_root_path' => 'D:/JianyingPro Drafts/',
  'draft_meta_info' => '{
  "draft_cloud_capcut_purchase_info": "",
  "draft_cloud_last_action_download": false,
  "draft_cloud_purchase_info": "",
  "draft_cloud_template_id": "",
  "draft_cloud_tutorial_info": "",
  "draft_cloud_videocut_purchase_info": "",
  "draft_cover": "",
  "draft_deeplink_url": "",
  "draft_enterprise_info": {
    "draft_enterprise_extra": "",
    "draft_enterprise_id": "",
    "draft_enterprise_name": ""
  },
  "draft_fold_path": "",
  "draft_id": "",
  "draft_is_article_video_draft": false,
  "draft_is_from_deeplink": "false",
  "draft_materials": [
    { "type": 0, "value": [] },
    { "type": 1, "value": [] },
    { "type": 2, "value": [] },
    { "type": 3, "value": [] },
    { "type": 6, "value": [] },
    { "type": 7, "value": [] },
    { "type": 8, "value": [] }
  ],
  "draft_materials_copied_info": [],
  "draft_name": "",
  "draft_new_version": "",
  "draft_removable_storage_device": "",
  "draft_root_path": "",
  "draft_segment_extra_info": [],
  "draft_timeline_materials_size_": 0,
  "tm_draft_cloud_completed": "",
  "tm_draft_cloud_modified": 0,
  "tm_draft_create": 0,
  "tm_draft_modified": 0,
  "tm_duration": 0
}',
  'draft_content' => '{
    "canvas_config": {
        "height": 1920,
        "ratio": "original",
        "width": 1920
    },
    "color_space": 0,
    "config": {
        "adjust_max_index": 1,
        "attachment_info": [],
        "combination_max_index": 1,
        "export_range": null,
        "extract_audio_last_index": 1,
        "lyrics_recognition_id": "",
        "lyrics_sync": true,
        "lyrics_taskinfo": [],
        "maintrack_adsorb": true,
        "material_save_mode": 0,
        "original_sound_last_index": 1,
        "record_audio_last_index": 1,
        "sticker_max_index": 1,
        "subtitle_recognition_id": "",
        "subtitle_sync": true,
        "subtitle_taskinfo": [],
        "system_font_list": [],
        "video_mute": false,
        "zoom_info_params": null
    },
    "cover": null,
    "create_time": 0,
    "duration": 0,
    "extra_info": null,
    "fps": 30.0,
    "free_render_index_mode_on": false,
    "group_container": null,
    "id": "2AA5CCA4-83BF-46aa-B0CE-DC019CFD52FC",
    "keyframe_graph_list": [],
    "keyframes": {
        "adjusts": [],
        "audios": [],
        "effects": [],
        "filters": [],
        "handwrites": [],
        "stickers": [],
        "texts": [],
        "videos": []
    },
    "last_modified_platform": {
        "app_id": 3704,
        "app_source": "lv",
        "app_version": "4.3.1",
        "device_id": "b045139fe2412ca7399978cc929ea773",
        "hard_disk_id": "a029880b76c8bfc839361046db4cf262",
        "mac_address": "70e497d276a268e7e4235809962cccf0,d9aed9fab7102f4f36bd91f70f9b043e,10d2717e7d06a80d409fbb21516ebec0",
        "os": "windows",
        "os_version": "10.0.19045"
    },
    "materials": {
        "audio_balances": [],
        "audio_effects": [],
        "audio_fades": [],
        "audios": [],
        "beats": [],
        "canvases": [],
        "chromas": [],
        "color_curves": [],
        "drafts": [],
        "effects": [],
        "green_screens": [],
        "handwrites": [],
        "hsl": [],
        "images": [],
        "log_color_wheels": [],
        "manual_deformations": [],
        "masks": [],
        "material_animations": [],
        "material_colors": [],
        "placeholders": [],
        "plugin_effects": [],
        "primary_color_wheels": [],
        "realtime_denoises": [],
        "sound_channel_mappings": [],
        "speeds": [],
        "stickers": [],
        "tail_leaders": [],
        "text_templates": [],
        "texts": [],
        "transitions": [],
        "video_effects": [],
        "video_trackings": [],
        "videos": []
    },
    "mutable_config": null,
    "name": "",
    "new_version": "77.0.0",
    "platform": {
        "app_id": 3704,
        "app_source": "lv",
        "app_version": "4.3.1",
        "device_id": "b045139fe2412ca7399978cc929ea773",
        "hard_disk_id": "a029880b76c8bfc839361046db4cf262",
        "mac_address": "70e497d276a268e7e4235809962cccf0,d9aed9fab7102f4f36bd91f70f9b043e,10d2717e7d06a80d409fbb21516ebec0",
        "os": "windows",
        "os_version": "10.0.19045"
    },
    "relationships": [],
    "render_index_track_mode_on": false,
    "retouch_cover": null,
    "source": "default",
    "static_cover_image_path": "",
    "tracks": [],
    "update_time": 0,
    "version": 360000
}',
  'default_positive_prompt' => 'masterpiece, best quality,',
  'default_negative_prompt' => 'NSFW, (worst quality:2), (low quality:2), (normal quality:2), lowres, normal quality, ((monochrome)), ((grayscale)), skin spots, acnes, skin blemishes, age spot, (ugly:1.331), (duplicate:1.331), (morbid:1.21), (mutilated:1.21), (tranny:1.331), mutated hands, (poorly drawn hands:1.5), blurry, (bad anatomy:1.21), (bad proportions:1.331), extra limbs, (disfigured:1.331), (missing arms:1.331), (extra legs:1.331), (fused fingers:1.61051), (too many fingers:1.61051), (unclear eyes:1.331), lowers, bad hands, missing fingers, extra digit,bad hands, missing fingers, (((extra arms and legs))),nsfw',
  'appkey' => 'ApCa9VgDVHYjadNt',
  'stable_diffusion_url' => 'http://region-3.seetacloud.com:42050',
  'gpt_url' => 'https://api.closeai-proxy.xyz',
  'is_windows' => '1',
  'audio_time' => '10',
  'prompt_time' => '20',
  'txt2img_time' => '60',
  'draft_time' => '2',
);
